name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # Fetch the last 2 commits to compare changes

      - name: Get GitHub Actions IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # Change to your AWS region

      - name: Add GitHub Actions IP to Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --region us-east-2 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32


      - name: Build and Deploy Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure Node.js and npm are installed
            if ! command -v node &> /dev/null; then
              curl -sL https://rpm.nodesource.com/setup_18.x | sudo bash -
              sudo yum install -y nodejs
            fi
            
            cd /home/ec2-user
            cd gymii_ai_dashboard
            # Update codebase
            git fetch origin
            git reset --hard origin/main
            
            # Install frontend dependencies and build
            npm install
            
            # Set host environment variables for Vite
            export VITE_ALLOWED_HOSTS=staging.gymii.ai
            
            # Build with production environment
            npm run build
            sudo chmod -R 755 /home/ec2-user/gymii_ai_dashboard/dist
            
            # Install backend dependencies if not already done
            pip install -r backend/requirements.txt
            
            # Start backend in production mode
            cd backend
            export FLASK_ENV=production
            export FLASK_APP=run.py
            export PORT=5500
            sudo systemctl restart gymii-dashboard.service
            
          

      - name: Remove GitHub Actions IP from Security Group
        if: always() # This ensures the step runs even if previous steps fail
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ secrets.AWS_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --region us-east-2 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
